name: Update NBA Data

on:
  schedule:
    - cron: '0 7 18-31 10 *'
    - cron: '0 7 * 11-12 *'
    - cron: '0 7 * 1-6 *'
    - cron: '0 7 1-12 7 *'
  workflow_dispatch:
    inputs:
      start_year:
        required: false
        type: string
      end_year:
        required: false
        type: string
      rescrape:
        required: false
        default: true
        type: boolean

jobs:
  update_nba_data:
    runs-on: ${{ matrix.config.os }}
    name: Update NBA Data ${{ inputs.start_year }}-${{ inputs.end_year }} (Rescrape? ${{ inputs.rescrape }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      START_YEAR: ${{ inputs.start_year }}
      END_YEAR: ${{ inputs.end_year }}
      RESCRAPE: ${{ inputs.rescrape }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setting up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            sportsdataverse/hoopR
            sportsdataverse/sportsdataverse-data
            ropensci/piggyback

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      # Tells Github to run the file `scraper.py` from your repository
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Check for Inputs
        if: ${{ env.START_YEAR == ''}}
        run: |
          echo START_YEAR=$(Rscript -e "hoopR::most_recent_nba_season()") >> $GITHUB_ENV
          echo END_YEAR=$(Rscript -e "hoopR::most_recent_nba_season()") >> $GITHUB_ENV
      - name: Run Python and R Process scripts
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          bash scripts/daily_nba_R_processor.sh -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }} -r ${{ env.RESCRAPE }}
